#ifndef PORT_CE_H_
#define PORT_CE_H_

#define PORT_NOTUSED_PIN0_GIOA	PIN0
#define PORT_NOTUSED_PIN1_GIOA	PIN1
#define PORT_CAN_ERROR			PIN2
#define PORT_CAN_INHIBIT		PIN3
#define PORT_LOW_BATTERY		PIN4
#define PORT_NOTUSED_PIN5_GIOA	PIN5
#define PORT_NOTUSED_PIN6_GIOA	PIN6
#define PORT_NOTUSED_PIN7_GIOA	PIN7

#define PORT_FLASH_EN			PIN0
#define PORT_AUDIO_DIAG_EN		PIN1
#define PORT_NOTUSED_PIN2_GIOB	PIN2
#define PORT_CRADLE_WUP			PIN3
#define PORT_CAN_EN				PIN4
#define PORT_CAN_STB			PIN5
#define PORT_MUTE_ON			PIN6
#define PORT_MUTE_TB			PIN7

#define PORT_RLADDER_EN			PIN0
#define PORT_LED_GREEN_ON_OFF		PIN1
#define PORT_LED_GREEN_TB		PIN2
#define PORT_LED_RED_ON_OFF			PIN3
#define PORT_LED_RED_TB			PIN4
#define PORT_LED_DIAG_EN		PIN5
#define PORT_CRADLE_ON_OFF			PIN6
#define PORT_CRADLE_TB			PIN7

#define PORT_MON_WATCHDOG		PIN0
#define PORT_MON_BOOTS			PIN1
#define PORT_MON_NRESETS		PIN2
#define PORT_MON_PWRHOLD		PIN3


#endif /*PORT_CE_H_*/
