/* file: tcb.c, automatically generated by GENTMS470.EXE, Version: 3.10 */
/* from: C:\PROGRAMME\ECLIPSE-CPP\ECLIPSE\WORKSPACE\UHV-NAR\MOD\MOD_OSEK_DYN\CFG\UHV_NAR.oil */
/* at  : Thu Nov 10 09:24:19 2011 */
/* License 2400100185 for S1nn GmbH u. Co. KG, Infotainment and Connectivity */
/* Implementation: TMS470R1 */
/* Version of general code: 3.54b */

#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif
#define osdVrmGenMajRelNum 3
#define osdVrmGenMinRelNum 10
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

/* Start of invariant part */
#if defined USE_QUOTE_INCLUDES
 #include "osek.h"
#else
 #include <osek.h>
#endif
#if defined USE_QUOTE_INCLUDES
 #include "osekext.h"
#else
 #include <osekext.h>
#endif

   /* structure for standard counter (derived from system clock) */
   osqROM0 osqROM1 const osqROM2 AlarmBaseType osqROM3 oskAlarmDefinitions=
   {
      OSMAXALLOWEDVALUE,
      OSTICKSPERBASE,
      OSMINCYCLE
   };

   osqTcbRAM1 osqTcbRAM2 TickType osqTcbRAM3 osAlarmTime[osdNumberOfAlarms];
   #ifndef osdUseGeneratedFastAlarm
      osqTcbRAM1 osqTcbRAM2 uint8 osqTcbRAM3 osAlarmActivated[osdNumberOfAlarms];
      osqTcbRAM1 osqTcbRAM2 osHeapType osqTcbRAM3 osAlarmHeap[osdNumberOfAlarms+1];    /* Minimum Heap */
   #endif

   #if (osdNumberOfVarAlarms > 0)
   osqTcbRAM1 osqTcbRAM2 TickType osqTcbRAM3 osAlarmCycleTime[osdNumberOfVarAlarms];
   #endif

#if (CC==BCC2) || (CC==ECC2)
   #if (osdNumberOfPriorities > 0)
      osqTcbRAM1 osqTcbRAM2 osQEntryCountType osqTcbRAM3 osQReadyTaskHead[osdNumberOfPriorities];
      osqTcbRAM1 osqTcbRAM2 osQEntryCountType osqTcbRAM3 osQReadyTaskTail[osdNumberOfPriorities];
   #else
      osqTcbRAM1 osqTcbRAM2 osQEntryCountType osqTcbRAM3 osQReadyTaskHead[1];
      osqTcbRAM1 osqTcbRAM2 osQEntryCountType osqTcbRAM3 osQReadyTaskTail[1];
   #endif
#else
   #if (osdNumberOfPriorities > 0)
      osqTcbRAM1 osqTcbRAM2 TaskType osqTcbRAM3 osQReadyTask[osdNumberOfPriorities];
   #else
      osqTcbRAM1 osqTcbRAM2 TaskType osqTcbRAM3 osQReadyTask[1];
   #endif
#endif

#if ((CC == BCC2) || (CC == ECC2))
   #if (osdNumberOfAllTasks > 0)
      osqTcbRAM1 osqTcbRAM2 osActivationCountType osqTcbRAM3 osTcbActivationCount[osdNumberOfAllTasks];
   #else
      osqTcbRAM1 osqTcbRAM2 osActivationCountType osqTcbRAM3 osTcbActivationCount[1];
   #endif
#endif

#if (osdRTSize > 1)
   osqRAM1 osqRAM2 osPrioFlagType osqRAM3 osQReadyPrios[osdRTSize];
#else
   osqRAM1 osqRAM2 osPrioFlagType osqRAM3 osQReadyPrios;
#endif

#if (osdNumberOfAllTasks > 0)
   osqTcbRAM1 osqTcbRAM2 osTaskStateType osqTcbRAM3 osTcbTaskState[osdNumberOfAllTasks];
   osStackPtrType osqTcbRAM1 osqTcbRAM2 osqTcbRAM3 osTcbSP[osdNumberOfAllTasks];
   #if osdORTIDebug
   osqTcbRAM1 osqTcbRAM2 osPrioType osqTcbRAM3 osTcbActualPrio[osdNumberOfAllTasks];
   osqTcbRAM1 osqTcbRAM2 uint8 osqTcbRAM3 osTcbORTIServiceId[osdNumberOfAllTasks];
   #endif
   #if STATUS_LEVEL == EXTENDED_STATUS
    #if (osdNumberOfInternalResources > 0) || (osdNumberOfInterruptResources > 0)
     osqTcbRAM1 osqTcbRAM2 uint8 osqTcbRAM3 osTcbResourceCounter[osdNumberOfAllTasks];
    #else
     #if osdLib
      osqTcbRAM1 osqTcbRAM2 uint8 osqTcbRAM3 osTcbResourceCounter[osdNumberOfAllTasks];
     #endif
    #endif
   #endif
   #if osdEnableContextOverlay
   osqTcbRAM1 osqTcbRAM2 uint8 osqTcbRAM3 osTcbReturnAddressState[osdNumberOfAllTasks];
   #endif
#else
   osqTcbRAM1 osqTcbRAM2 osTaskStateType osqTcbRAM3 osTcbTaskState[1];
   osStackPtrType osqTcbRAM1 osqTcbRAM2 osqTcbRAM3 osTcbSP[1];
   #if osdORTIDebug
   osqTcbRAM1 osqTcbRAM2 osPrioType osqTcbRAM3 osTcbActualPrio[1];
   osqTcbRAM1 osqTcbRAM2 uint8 osqTcbRAM3 osTcbORTIServiceId[1];
   #endif
   #if STATUS_LEVEL == EXTENDED_STATUS
   #if (osdNumberOfInternalResources > 0) || (osdNumberOfInterruptResources > 0)
   osqTcbRAM1 osqTcbRAM2 uint8 osqTcbRAM3 osTcbResourceCounter[1];
    #else
     #if osdLib
      osqTcbRAM1 osqTcbRAM2 uint8 osqTcbRAM3 osTcbResourceCounter[1];
     #endif
   #endif
   #endif
   #if osdEnableContextOverlay
   osqTcbRAM1 osqTcbRAM2 uint8 osqTcbRAM3 osTcbReturnAddressState[1];
   #endif
#endif


   osqTcbRAM1 osqTcbRAM2 osPrioType osqTcbRAM3 osResSavedPrio[osdNumberOfAllResources];
   #if STATUS_LEVEL == EXTENDED_STATUS
      osqTcbRAM1 osqTcbRAM2 osResCounterType osqTcbRAM3 osResOccupationCounter[osdNumberOfAllResources];
   #endif
   #if ((STATUS_LEVEL == EXTENDED_STATUS) && osdEnableAssertions) || osdORTIDebug
      osqTcbRAM1 osqTcbRAM2 TaskType osqTcbRAM3 osResActualTask[osdNumberOfAllResources];
   #endif


   osqTcbRAM1 osqTcbRAM2 EventMaskType osqTcbRAM3 osTcbWaitEventMask[osdNumberOfExtendedTasks];

#if (osdNumberOfExtendedTasks > 0) || osdLib
   #if (osdNumberOfExtendedTasks == 0) && osdLib
   osqTcbRAM1 osqTcbRAM2 EventMaskType osqTcbRAM3 osTcbSetEventMask[1];
   #else
   osqTcbRAM1 osqTcbRAM2 EventMaskType osqTcbRAM3 osTcbSetEventMask[osdNumberOfExtendedTasks];
   #endif
#endif

#if (osdNumberOfSemaphores > 0)
   osqTcbRAM1 osqTcbRAM2 uint8 osqTcbRAM3 osSemaphoreState[osdNumberOfSemaphores];
   #if (osdNumberOfExtendedTasks == 0) && osdLib
   osqTcbRAM1 osqTcbRAM2 SemaphoreType osqTcbRAM3 osTcbWaitForSemaphore[1];
   #else
   osqTcbRAM1 osqTcbRAM2 SemaphoreType osqTcbRAM3 osTcbWaitForSemaphore[osdNumberOfExtendedTasks];
   #endif
#endif

#if osdLib
   osqROM0 osqROM1 const osqROM2 osRTSizeType    osqROM3 oskRTSize= osdRTSize;
   osqROM0 osqROM1 const osqROM2 osTaskIndexType osqROM3 oskNumberOfAllTasks=      osdNumberOfAllTasks;
   osqROM0 osqROM1 const osqROM2 osTaskIndexType osqROM3 oskNumberOfExtendedTasks= osdNumberOfExtendedTasks;
   osqROM0 osqROM1 const osqROM2 osPrioType      osqROM3 oskNumberOfPriorities=    osdNumberOfPriorities;

   osqROM0 osqROM1 const osqROM2 osResourceIndexType osqROM3 oskNumberOfAllResources= osdNumberOfAllResources;
   osqROM0 osqROM1 const osqROM2 osResourceIndexType osqROM3 oskNumberOfTaskResources= osdNumberOfTaskResources;
   osqROM0 osqROM1 const osqROM2 osResourceIndexType osqROM3 oskNumberOfInterruptResources= osdNumberOfInterruptResources;
   osqROM0 osqROM1 const osqROM2 osResourceIndexType osqROM3 oskNumberOfInternalResources= osdNumberOfInternalResources;

   osqROM0 osqROM1 const osqROM2 osAlarmIndexType osqROM3 oskNumberOfAlarms=         osdNumberOfAlarms;
   osqROM0 osqROM1 const osqROM2 osAlarmIndexType osqROM3 oskNumberOfVarAlarms=      osdNumberOfVarAlarms;
   osqROM0 osqROM1 const osqROM2 osAlarmIndexType osqROM3 oskNumberOfVarHeapAlarms=  osdNumberOfVarHeapAlarms;
   osqROM0 osqROM1 const osqROM2 osAlarmIndexType osqROM3 oskNumberOfStatHeapAlarms= osdNumberOfStatHeapAlarms;
   
   osqROM0 osqROM1 const osqROM2 TickType         osqROM3 oskMaxAllowedValue=        OSMAXALLOWEDVALUE;
   osqROM0 osqROM1 const osqROM2 TickType         osqROM3 oskMinCycle=               OSMINCYCLE;
   osqROM0 osqROM1 const osqROM2 TickType         osqROM3 oskTicksPerBase=           OSTICKSPERBASE;

#endif
/* End of invariant part */
#if defined osdUseGeneratedFastAlarm
osqFunc1 void osqFunc2 osCheckAlarms(void)  /* PRQA S 1505 */  /* might be called intern or extern */
{
   osqPRAM1 osqPRAM2 TickType osqPRAM3 *aPtr = osAlarmTime;
   if ((*aPtr) != 0)    /* CTA_HOST */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_HOST is expired */
         (*aPtr) = osAlarmCycleTime[CTA_HOST];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_HOST] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsHostTask_10ms,evActivateHostTask_10ms);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_MONITOR */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_MONITOR is expired */
         (*aPtr) = osAlarmCycleTime[CTA_MONITOR];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_MONITOR] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsMonitorTask_50ms,evActivateMonitorTask_50ms);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_DRIVER */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_DRIVER is expired */
         (*aPtr) = osAlarmCycleTime[CTA_DRIVER];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_DRIVER] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsDriverTask_1ms,evActivateDriverTask_1ms);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_DATABASE_EEPROM_WRITE */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_DATABASE_EEPROM_WRITE is expired */
         (*aPtr) = osAlarmCycleTime[CTA_DATABASE_EEPROM_WRITE];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_DATABASE_EEPROM_WRITE] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsDatabaseTask_event,evDatabaseCyclicEepromWrite);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_APP */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_APP is expired */
         (*aPtr) = osAlarmCycleTime[CTA_APP];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_APP] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsAppTask_event_100ms,evActivateAppTask_event_100ms);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_APP_PHONE_BAP_IND */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_APP_PHONE_BAP_IND is expired */
         (*aPtr) = osAlarmCycleTime[CTA_APP_PHONE_BAP_IND];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_APP_PHONE_BAP_IND] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsAppTask_event_100ms,evAppTaskPhoneBapInd);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_APP_PHONE_FCT_PENDING */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_APP_PHONE_FCT_PENDING is expired */
         (*aPtr) = osAlarmCycleTime[CTA_APP_PHONE_FCT_PENDING];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_APP_PHONE_FCT_PENDING] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsAppTask_event_100ms,evAppTaskPhoneFctPending);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_APP_PHONEBOOK_BAP_IND */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_APP_PHONEBOOK_BAP_IND is expired */
         (*aPtr) = osAlarmCycleTime[CTA_APP_PHONEBOOK_BAP_IND];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_APP_PHONEBOOK_BAP_IND] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsAppTask_event_100ms,evAppTaskPhoneBookBapInd);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_APP_PHONEBOOK_FCT_PENDING */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_APP_PHONEBOOK_FCT_PENDING is expired */
         (*aPtr) = osAlarmCycleTime[CTA_APP_PHONEBOOK_FCT_PENDING];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_APP_PHONEBOOK_FCT_PENDING] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsAppTask_event_100ms,evAppTaskPhoneBookFctPending);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_APP_MDI_BAP_IND */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_APP_MDI_BAP_IND is expired */
         (*aPtr) = osAlarmCycleTime[CTA_APP_MDI_BAP_IND];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_APP_MDI_BAP_IND] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsAppTask_event_100ms,evAppTaskMdiBapInd);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_APP_MDI_FCT_PENDING */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_APP_MDI_FCT_PENDING is expired */
         (*aPtr) = osAlarmCycleTime[CTA_APP_MDI_FCT_PENDING];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_APP_MDI_FCT_PENDING] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsAppTask_event_100ms,evAppTaskMdiFctPending);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_ERM_BT_VISIBILITY_TIMER */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_ERM_BT_VISIBILITY_TIMER is expired */
         (*aPtr) = osAlarmCycleTime[CTA_ERM_BT_VISIBILITY_TIMER];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_ERM_BT_VISIBILITY_TIMER] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsAppTask_event_100ms,evAppTaskERMBTVisibleTimer);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_SYSTEM */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_SYSTEM is expired */
         (*aPtr) = osAlarmCycleTime[CTA_SYSTEM];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_SYSTEM] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsSystemTask_event,evActivateSystemTask_event);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_HOST_TASK_CYCLIC_CAN_TX_MSG */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_HOST_TASK_CYCLIC_CAN_TX_MSG is expired */
         (*aPtr) = osAlarmCycleTime[CTA_HOST_TASK_CYCLIC_CAN_TX_MSG];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_HOST_TASK_CYCLIC_CAN_TX_MSG] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsHostTask_10ms,evHostTaskCyclicTxMsg);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_VCR_PENDING */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_VCR_PENDING is expired */
         (*aPtr) = osAlarmCycleTime[CTA_VCR_PENDING];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_VCR_PENDING] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsAppTask_event_100ms,evAppTaskVCRPending);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_ERM_PENDING */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_ERM_PENDING is expired */
         (*aPtr) = osAlarmCycleTime[CTA_ERM_PENDING];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_ERM_PENDING] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsAppTask_event_100ms,evAppTaskERMPending);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_APP_PHONEBOOK_PB_INIT_PENDING */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_APP_PHONEBOOK_PB_INIT_PENDING is expired */
         (*aPtr) = osAlarmCycleTime[CTA_APP_PHONEBOOK_PB_INIT_PENDING];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_APP_PHONEBOOK_PB_INIT_PENDING] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsAppTask_event_100ms,evAppTaskPhoneBookBapFctPending);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_WD */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_WD is expired */
         (*aPtr) = osAlarmCycleTime[CTA_WD];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_WD] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsDatabaseTask_event,evTriggerWD);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_ASG_SV_TIMEOUT */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_ASG_SV_TIMEOUT is expired */
         (*aPtr) = osAlarmCycleTime[CTA_ASG_SV_TIMEOUT];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_ASG_SV_TIMEOUT] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsAppTask_event_100ms,evAppTaskKpbSupervision);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_FRAME_DATA_ACK_TIMEOUT */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_FRAME_DATA_ACK_TIMEOUT is expired */
         (*aPtr) = osAlarmCycleTime[CTA_FRAME_DATA_ACK_TIMEOUT];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_FRAME_DATA_ACK_TIMEOUT] = 0;
         }
#endif /*osdUseHeapAlarm*/
         KPB_cbFrameDataAckTimeout();

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_APP_SMS_FCT_PENDING */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_APP_SMS_FCT_PENDING is expired */
         (*aPtr) = osAlarmCycleTime[CTA_APP_SMS_FCT_PENDING];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_APP_SMS_FCT_PENDING] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsAppTask_event_100ms,evAppTaskSmsFctPending);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_APP_PHONEBOOK_BAP_FCT_PENDING */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_APP_PHONEBOOK_BAP_FCT_PENDING is expired */
         (*aPtr) = osAlarmCycleTime[CTA_APP_PHONEBOOK_BAP_FCT_PENDING];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_APP_PHONEBOOK_BAP_FCT_PENDING] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsAppTask_event_100ms,evAppTaskPhoneBookBapFctPending);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_APP_PHONE_BAP_FCT_PENDING */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_APP_PHONE_BAP_FCT_PENDING is expired */
         (*aPtr) = osAlarmCycleTime[CTA_APP_PHONE_BAP_FCT_PENDING];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_APP_PHONE_BAP_FCT_PENDING] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsAppTask_event_100ms,evAppTaskPhoneBapFctPending);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_MONITOR_AUDIO */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_MONITOR_AUDIO is expired */
         (*aPtr) = osAlarmCycleTime[CTA_MONITOR_AUDIO];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_MONITOR_AUDIO] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsMonitorTask_50ms,evMonitorTask_MonitorAudio_for_DTC);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_APP_SD_FCT_PENDING */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_APP_SD_FCT_PENDING is expired */
         (*aPtr) = osAlarmCycleTime[CTA_APP_SD_FCT_PENDING];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_APP_SD_FCT_PENDING] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsAppTask_event_100ms,evAppTaskSdFctPending);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_KPB_FCT_PENDING */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_KPB_FCT_PENDING is expired */
         (*aPtr) = osAlarmCycleTime[CTA_KPB_FCT_PENDING];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_KPB_FCT_PENDING] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsAppTask_event_100ms,evAppTaskKpbPending);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_MFL_LONGPRESS_TIMER */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_MFL_LONGPRESS_TIMER is expired */
         (*aPtr) = osAlarmCycleTime[CTA_MFL_LONGPRESS_TIMER];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_MFL_LONGPRESS_TIMER] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsAppTask_event_100ms,evAppTaskRollRadLongPressTimer);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_APP_SD_FRAME_TIMEOUT */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_APP_SD_FRAME_TIMEOUT is expired */
         (*aPtr) = osAlarmCycleTime[CTA_APP_SD_FRAME_TIMEOUT];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_APP_SD_FRAME_TIMEOUT] = 0;
         }
#endif /*osdUseHeapAlarm*/
         APP_SD_cbFrameTimeout();

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_APP_DEVICE_FCT_PENDING */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_APP_DEVICE_FCT_PENDING is expired */
         (*aPtr) = osAlarmCycleTime[CTA_APP_DEVICE_FCT_PENDING];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_APP_DEVICE_FCT_PENDING] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsAppTask_event_100ms,evAppTaskDeviceFctPending);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_VCR_SUPERVISOR */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_VCR_SUPERVISOR is expired */
         (*aPtr) = osAlarmCycleTime[CTA_VCR_SUPERVISOR];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_VCR_SUPERVISOR] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsAppTask_event_100ms,evAppTaskVCRSupervisor);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_HOST_TASK_CYCLIC_CAN_ASR_TX_MSG */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_HOST_TASK_CYCLIC_CAN_ASR_TX_MSG is expired */
         (*aPtr) = osAlarmCycleTime[CTA_HOST_TASK_CYCLIC_CAN_ASR_TX_MSG];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_HOST_TASK_CYCLIC_CAN_ASR_TX_MSG] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsHostTask_10ms,evHostTaskASRCyclicTxMsg);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_UART_SUPERVISION */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_UART_SUPERVISION is expired */
         (*aPtr) = osAlarmCycleTime[CTA_UART_SUPERVISION];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_UART_SUPERVISION] = 0;
         }
#endif /*osdUseHeapAlarm*/
         ERM_UartSupervision();

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_HOST_ASR_TRIGGER */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_HOST_ASR_TRIGGER is expired */
         (*aPtr) = osAlarmCycleTime[CTA_HOST_ASR_TRIGGER];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_HOST_ASR_TRIGGER] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsHostTask_10ms,evHostTaskASRTrigger);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_APP_KPB_BAP_IND */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_APP_KPB_BAP_IND is expired */
         (*aPtr) = osAlarmCycleTime[CTA_APP_KPB_BAP_IND];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_APP_KPB_BAP_IND] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsAppTask_event_100ms,evAppTaskKpbBapInd);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_DRIVER_TIMER_10MS */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_DRIVER_TIMER_10MS is expired */
         (*aPtr) = osAlarmCycleTime[CTA_DRIVER_TIMER_10MS];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_DRIVER_TIMER_10MS] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsDriverTask_1ms,evDriverTask_TimerForButtonDetection_10ms);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_CONTEXT_MAN_HANDLE_CALLS */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_CONTEXT_MAN_HANDLE_CALLS is expired */
         (*aPtr) = osAlarmCycleTime[CTA_CONTEXT_MAN_HANDLE_CALLS];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_CONTEXT_MAN_HANDLE_CALLS] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsAppTask_event_100ms,evAppTaskContaxtManHandleCalls);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_APP_PHONEBOOK_BAP_ACT_PB_PEND */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_APP_PHONEBOOK_BAP_ACT_PB_PEND is expired */
         (*aPtr) = osAlarmCycleTime[CTA_APP_PHONEBOOK_BAP_ACT_PB_PEND];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_APP_PHONEBOOK_BAP_ACT_PB_PEND] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsAppTask_event_100ms,evAppTaskPhoneBookBapFctPending);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_APP_DIAG_WAIT_FOR_APP_CB */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_APP_DIAG_WAIT_FOR_APP_CB is expired */
         (*aPtr) = osAlarmCycleTime[CTA_APP_DIAG_WAIT_FOR_APP_CB];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_APP_DIAG_WAIT_FOR_APP_CB] = 0;
         }
#endif /*osdUseHeapAlarm*/
         APP_DIAG_vHandlePendingResponseFromApplication();

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_APP_MDI_BAP_FCT_PENDING */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_APP_MDI_BAP_FCT_PENDING is expired */
         (*aPtr) = osAlarmCycleTime[CTA_APP_MDI_BAP_FCT_PENDING];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_APP_MDI_BAP_FCT_PENDING] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsAppTask_event_100ms,evAppTaskMdiBapFctPending);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_KPB_DISPLAY_STATUS_OFF */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_KPB_DISPLAY_STATUS_OFF is expired */
         (*aPtr) = osAlarmCycleTime[CTA_KPB_DISPLAY_STATUS_OFF];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_KPB_DISPLAY_STATUS_OFF] = 0;
         }
#endif /*osdUseHeapAlarm*/
         KPB_cbDisplayStatusOff();

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_ERM_STOP_JINGLE */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_ERM_STOP_JINGLE is expired */
         (*aPtr) = osAlarmCycleTime[CTA_ERM_STOP_JINGLE];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_ERM_STOP_JINGLE] = 0;
         }
#endif /*osdUseHeapAlarm*/
         ctaERMStopJingle_cb();

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_APP_PHONE_OUTGOING_CALL_INDICATION_TIMER */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_APP_PHONE_OUTGOING_CALL_INDICATION_TIMER is expired */
         (*aPtr) = osAlarmCycleTime[CTA_APP_PHONE_OUTGOING_CALL_INDICATION_TIMER];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_APP_PHONE_OUTGOING_CALL_INDICATION_TIMER] = 0;
         }
#endif /*osdUseHeapAlarm*/
         APP_PHONE_cbOutgoingCallIndicationTimeout();

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_BTMOD_TIMEOUT */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_BTMOD_TIMEOUT is expired */
         (*aPtr) = osAlarmCycleTime[CTA_BTMOD_TIMEOUT];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_BTMOD_TIMEOUT] = 0;
         }
#endif /*osdUseHeapAlarm*/
         ctaBtTimeout_cb();

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_APP_PHONE_PATR_WORKAROUND_TIMER */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_APP_PHONE_PATR_WORKAROUND_TIMER is expired */
         (*aPtr) = osAlarmCycleTime[CTA_APP_PHONE_PATR_WORKAROUND_TIMER];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_APP_PHONE_PATR_WORKAROUND_TIMER] = 0;
         }
#endif /*osdUseHeapAlarm*/
         APP_PHONE_cbOnPatrTimeout();

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_LOGI_BUT_MAN_ROLL_BUTTON */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_LOGI_BUT_MAN_ROLL_BUTTON is expired */
         (*aPtr) = osAlarmCycleTime[CTA_LOGI_BUT_MAN_ROLL_BUTTON];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_LOGI_BUT_MAN_ROLL_BUTTON] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsAppTask_event_100ms,evAppTaskMFLKeys);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_APP_PHONEBOOK_SORTING_TIMEOUT */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_APP_PHONEBOOK_SORTING_TIMEOUT is expired */
         (*aPtr) = osAlarmCycleTime[CTA_APP_PHONEBOOK_SORTING_TIMEOUT];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_APP_PHONEBOOK_SORTING_TIMEOUT] = 0;
         }
#endif /*osdUseHeapAlarm*/
         APP_PHONEBOOK_cbPbSortingTimeout();

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_APP_CAN_TO_NACHLAUFZEIT */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_APP_CAN_TO_NACHLAUFZEIT is expired */
         (*aPtr) = osAlarmCycleTime[CTA_APP_CAN_TO_NACHLAUFZEIT];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_APP_CAN_TO_NACHLAUFZEIT] = 0;
         }
#endif /*osdUseHeapAlarm*/
         APP_CAN_cbNachlaufzeitTimeout();

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_HOST_R2FS_DIAG_RETRY */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_HOST_R2FS_DIAG_RETRY is expired */
         (*aPtr) = osAlarmCycleTime[CTA_HOST_R2FS_DIAG_RETRY];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_HOST_R2FS_DIAG_RETRY] = 0;
         }
#endif /*osdUseHeapAlarm*/
         SDS_UDS_RetryMechanismR2FS();

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_APP_DIAG_RETRY_BUSY */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_APP_DIAG_RETRY_BUSY is expired */
         (*aPtr) = osAlarmCycleTime[CTA_APP_DIAG_RETRY_BUSY];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_APP_DIAG_RETRY_BUSY] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsAppTask_event_100ms,evAppTaskDiagnoseRequest);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_APP_PHONE_BAP_REQUEST_PENDING */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_APP_PHONE_BAP_REQUEST_PENDING is expired */
         (*aPtr) = osAlarmCycleTime[CTA_APP_PHONE_BAP_REQUEST_PENDING];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_APP_PHONE_BAP_REQUEST_PENDING] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsAppTask_event_100ms,evAppTaskPhoneBapRequestPending);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_HOST_ONOFF_INFO_SLEEP_IND */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_HOST_ONOFF_INFO_SLEEP_IND is expired */
         (*aPtr) = osAlarmCycleTime[CTA_HOST_ONOFF_INFO_SLEEP_IND];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_HOST_ONOFF_INFO_SLEEP_IND] = 0;
         }
#endif /*osdUseHeapAlarm*/
         (void) osSysSetEvent(OsHostTask_10ms,evHostTaskOnOffInfoSleepInd);

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* CTA_DEH_EE_WRITE_TIME */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* CTA_DEH_EE_WRITE_TIME is expired */
         (*aPtr) = osAlarmCycleTime[CTA_DEH_EE_WRITE_TIME];
#if (osdUseHeapAlarm != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[CTA_DEH_EE_WRITE_TIME] = 0;
         }
#endif /*osdUseHeapAlarm*/
         SDS_UDS_Wait_DEH_Write_Finish();

         osSetAlarmLevel(); /* enable interrupts */
         osDisableLevel();  /* disable interrupts */

      }
   }
} /* END OF alarm checking function */
#endif /*osdUseGeneratedFastAlarm*/



osStackDataType osSystemStack[50];
osStackDataType osSupervisorStack[50];
osStackDataType osIrqStack[osdIrqStackSize/4]; /* PRQA S 1504 */  /* PRQA S 3408 */ /* stack might be accessed from assembler code */

/* Task stacks generated in dependence on the stack model: */
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStack0 [115];  /* PRQA S 1504 */  /* PRQA S 3408 */ /* stack might be accessed from assembler code */ 
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStack1 [375];  /* PRQA S 1504 */  /* PRQA S 3408 */ /* stack might be accessed from assembler code */ 
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStack2 [60];  /* PRQA S 1504 */  /* PRQA S 3408 */ /* stack might be accessed from assembler code */ 
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStack3 [100];  /* PRQA S 1504 */  /* PRQA S 3408 */ /* stack might be accessed from assembler code */ 
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStack4 [75];  /* PRQA S 1504 */  /* PRQA S 3408 */ /* stack might be accessed from assembler code */ 
osqStack1 osqStack2 osStackDataType osqStack3 osTaskStack5 [50];  /* PRQA S 1504 */  /* PRQA S 3408 */ /* stack might be accessed from assembler code */ 

osqROM0 osStackPtrType osqROM1 const osqROM2 osqROM3 oskTcbStackTop[osdNumberOfAllTasks]=
{
   osAssignStack(osTaskStack0),
   osAssignStack(osTaskStack1),
   osAssignStack(osTaskStack2),
   osAssignStack(osTaskStack3),
   osAssignStack(osTaskStack4),
   osAssignStack(osTaskStack5),
};

#if osdStackCheck
osqROM0 osStackPtrType osqROM1 const osqROM2 osqROM3 oskTcbStackBottom[osdNumberOfAllTasks]=
{
   osBottomOfStack(osTaskStack0),
   osBottomOfStack(osTaskStack1),
   osBottomOfStack(osTaskStack2),
   osBottomOfStack(osTaskStack3),
   osBottomOfStack(osTaskStack4),
   osBottomOfStack(osTaskStack5),
};

#endif

#if (CC == BCC2) || (CC == ECC2)
static osqTcbRAM1 osqTcbRAM2 TaskType osqTcbRAM3 osQTaskActivation_0[2];
static osqTcbRAM1 osqTcbRAM2 TaskType osqTcbRAM3 osQTaskActivation_1[2];
static osqTcbRAM1 osqTcbRAM2 TaskType osqTcbRAM3 osQTaskActivation_2[2];
static osqTcbRAM1 osqTcbRAM2 TaskType osqTcbRAM3 osQTaskActivation_3[2];
static osqTcbRAM1 osqTcbRAM2 TaskType osqTcbRAM3 osQTaskActivation_4[2];
static osqTcbRAM1 osqTcbRAM2 TaskType osqTcbRAM3 osQTaskActivation_5[2];
static osqTcbRAM1 osqTcbRAM2 TaskType osqTcbRAM3 osQTaskActivation_6[2];
static osqTcbRAM1 osqTcbRAM2 TaskType osqTcbRAM3 osQTaskActivation_7[2];
static osqTcbRAM1 osqTcbRAM2 TaskType osqTcbRAM3 osQTaskActivation_8[2];
static osqTcbRAM1 osqTcbRAM2 TaskType osqTcbRAM3 osQTaskActivation_9[2];
static osqTcbRAM1 osqTcbRAM2 TaskType osqTcbRAM3 osQTaskActivation_10[2];
static osqTcbRAM1 osqTcbRAM2 TaskType osqTcbRAM3 osQTaskActivation_11[2];
static osqTcbRAM1 osqTcbRAM2 TaskType osqTcbRAM3 osQTaskActivation_12[2];
static osqTcbRAM1 osqTcbRAM2 TaskType osqTcbRAM3 osQTaskActivation_13[2];

osqROM0 osqPTcbRAM1 osqPTcbRAM2 TaskType osqPTcbRAM3 * osqROM1 const osqROM2 osqROM3 oskQActivationQueues[osdNumberOfPriorities]=
{
   osQTaskActivation_0,
   osQTaskActivation_1,
   osQTaskActivation_2,
   osQTaskActivation_3,
   osQTaskActivation_4,
   osQTaskActivation_5,
   osQTaskActivation_6,
   osQTaskActivation_7,
   osQTaskActivation_8,
   osQTaskActivation_9,
   osQTaskActivation_10,
   osQTaskActivation_11,
   osQTaskActivation_12,
   osQTaskActivation_13,
};

osqROM0 osqROM1 const osqROM2 osQEntryCountType osqROM3 oskQMaxActivations[osdNumberOfPriorities]=
{
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
};

#endif

osqROM0 osTaskFctType osqROM1 const osqROM2 osqROM3 oskTcbTaskStartAddress[osdNumberOfAllTasks] = {
   OsHostTask_10msfunc,
   OsAppTask_event_100msfunc,
   OsSystemTask_eventfunc,
   OsDriverTask_1msfunc,
   OsMonitorTask_50msfunc,
   OsDatabaseTask_eventfunc,
};

#if osdMixedPreempt
osqROM0 osqROM1 const osqROM2 osTaskPreemptionType osqROM3 oskTcbTaskPreemption[osdNumberOfAllTasks] = {
   osdTaskTypeNonPreempt,
   osdTaskTypePreempt,
   osdTaskTypeNonPreempt,
   osdTaskTypePreempt,
   osdTaskTypePreempt,
   osdTaskTypePreempt,
};
#endif /* osdMixedPreempt */

osqROM0 osqROM1 const osqROM2 osTaskFlagType osqROM3 oskTcbTaskFlags[osdNumberOfAllTasks] = {
 osdTaskFlagScheduleAllowed,
 osdTaskFlagScheduleAllowed,
 osdTaskFlagScheduleAllowed,
 osdTaskFlagScheduleAllowed,
 osdTaskFlagScheduleAllowed,
 osdTaskFlagScheduleAllowed,
};

osqROM0 osqROM1 const osqROM2 uint8 osqROM3 oskTcbAutoStart[osdNumberOfAllTasks] = {
   0x01, /* OsHostTask_10ms*/
   0x00, /* OsAppTask_event_100ms */
   0x00, /* OsSystemTask_event */
   0x00, /* OsDriverTask_1ms */
   0x00, /* OsMonitorTask_50ms */
   0x00, /* OsDatabaseTask_event */
};

osqROM0 osqROM1 const osqROM2 osPrioFlagType osqROM3 oskTcbReadyPrioMask[osdNumberOfAllTasks] = {
   0x02000000U,
   0x00800000U,
   0x00400000U,
   0x00200000U,
   0x00080000U,
   0x00040000U,
};

#if (osdRTSize > 1)
osqROM0 osqROM1 const osqROM2 osPrioOffsetType osqROM3 oskTcbReadyPrioOffset[osdNumberOfAllTasks] = {
   0x00,
   0x00,
   0x00,
   0x00,
   0x00,
   0x00,
};
#endif

osqROM0 osqROM1 const osqROM2 osPrioType osqROM3 oskTcbHomePrio[osdNumberOfAllTasks]=
{
   6,
   8,
   9,
   10,
   12,
   13,
};

#if (CC == BCC2) || (CC == ECC2)
osqROM0 osqROM1 const osqROM2 osActivationCountType osqROM3 oskTcbAllowedActivations[osdNumberOfAllTasks]=
{
   1,
   1,
   1,
   1,
   1,
   1,
};
#endif

#if (osdGHSDebugSupport==1)
osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 * osqROM1 const osqROM2 osqROM3 oskTcbTaskName[osdNumberOfAllTasks]=
{
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"OsHostTask_10ms",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"OsAppTask_event_100ms",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"OsSystemTask_event",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"OsDriverTask_1ms",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"OsMonitorTask_50ms",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"OsDatabaseTask_event",
};
osqROM0 osqROM1 const osqROM2 uint16 osqROM3 oskTcbOILPrio[osdNumberOfAllTasks]=
{
   10,
   8,
   7,
   4,
   2,
   1,
};
#endif

#if osdEnableProcedures
osqROM0 osqROM1 const osqROM2 osContextOverlayType osqROM3 oskTcbContextOverlay[osdNumberOfAllTasks] = {
   0,
   0,
   0,
   0,
   0,
   0,
};
#endif /* osdEnableProcedures */

/* Resources */

#if ((!defined(osdGetResourceNotUsed)) || (!defined(osdReleaseResourceNotUsed)))
#if (osdGHSDebugSupport==1)
osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 * osqROM1 const osqROM2 osqROM3 oskResName[osdNumberOfAllResources]=
{
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CK5050_WRITE_Resource",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"EEPROM_LockResource",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"UART_LockResource",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CRC_LockResource",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"POOL_LockResource",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"DEH_LockResource",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"EEPROM_LAYOUT_LockResource",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"RES_SCHEDULER",
};

#endif

#if (STATUS_LEVEL == EXTENDED_STATUS) && osdEnableAssertions
osqROM0 osqROM1 const osqROM2 osResAccessMaskType osqROM3 oskResAccessMask[osdNumberOfAllResources][1]={
/* sequence of taskNumbers (!not priorities) */
   {    0x40000000U,   } /* CK5050_WRITE_Resource*/
  ,{    0xdc000000U,   } /* EEPROM_LockResource*/
  ,{    0xfc000000U,   } /* UART_LockResource*/
  ,{    0x08000000U,   } /* CRC_LockResource*/
  ,{    0xd0000000U,   } /* POOL_LockResource*/
  ,{    0xfc000000U,   } /* DEH_LockResource*/
  ,{    0xfc000000U,   } /* EEPROM_LAYOUT_LockResource*/
  ,{    0xfc000000U,   } /* RES_SCHEDULER*/
};

#endif /* (STATUS_LEVEL == EXTENDED_STATUS) && osdEnableAssertions */

osqROM0 osqROM1 const osqROM2 osPrioType osqROM3 oskResCeilingPrio[osdNumberOfAllResources]=
{
   (osPrioType)7,
   (osPrioType)5,
   (osPrioType)4,
   (osPrioType)11,
   (osPrioType)3,
   (osPrioType)2,
   (osPrioType)1,
   (osPrioType)0,
};

osqROM0 osqROM1 const osqROM2 osPrioFlagType osqROM3 oskResCeilingPrioMask[osdNumberOfTaskResources]=
{
   0x01000000U,
   0x04000000U,
   0x08000000U,
   0x00100000U,
   0x10000000U,
   0x20000000U,
   0x40000000U,
   0x80000000U,
};

#if (osdRTSize > 1)
osqROM0 osqROM1 const osqROM2 osPrioOffsetType osqROM3 oskResCeilingPrioOffset[osdNumberOfTaskResources]=
{
   0x00,
   0x00,
   0x00,
   0x00,
   0x00,
   0x00,
   0x00,
   0x00,
};
#endif

#endif /*((!defined(osdGetResourceNotUsed)) || (!defined(osdReleaseResourceNotUsed))) */

#if (osdNumberOfAllTasks>0)
#if ((osdNumberOfInternalResources > 0)||(osdLib==1))
osqROM0 osqROM1 const osqROM2 osPrioType osqROM3 oskResInternalCeilingPrio[osdNumberOfAllTasks]=
{
   (osPrioType) 0,
   (osPrioType) 0,
   (osPrioType) 0,
   (osPrioType) 0,
   (osPrioType) 0,
   (osPrioType) 0,
};

osqROM0 osqROM1 const osqROM2 osPrioFlagType osqROM3 oskResInternalCeilingPrioMask[osdNumberOfAllTasks]=
{
   0,
   0,
   0,
   0,
   0,
   0,
};

 #if ((osdRTSize > 1)||(osdLib==1))
osqROM0 osqROM1 const osqROM2 osPrioOffsetType osqROM3 oskResInternalCeilingPrioOffset[osdNumberOfAllTasks]=
{
   0,
   0,
   0,
   0,
   0,
   0,
};

#endif
#endif

#else
osqROM0 osqROM1 const osqROM2 osPrioType osqROM3 oskResInternalCeilingPrio[1]={0};
osqROM0 osqROM1 const osqROM2 osPrioFlagType osqROM3 oskResInternalCeilingPrioMask[1]={0};
osqROM0 osqROM1 const osqROM2 osPrioOffsetType osqROM3 oskResInternalCeilingPrioOffset[1]={0};
#endif
/* Counters */

/* Alarms */

#if (osdNumberOfAlarmActivateTask > 0) || (osdNumberOfAlarmSetEvent > 0)
/* task to activate or to event */
osqROM0 osqROM1 const osqROM2 TaskType osqROM3 oskAlarmTask[osdNumberOfAlarms]={
   OsHostTask_10ms, /* CTA_HOST*/
   OsMonitorTask_50ms, /* CTA_MONITOR*/
   OsDriverTask_1ms, /* CTA_DRIVER*/
   OsDatabaseTask_event, /* CTA_DATABASE_EEPROM_WRITE*/
   OsAppTask_event_100ms, /* CTA_APP*/
   OsAppTask_event_100ms, /* CTA_APP_PHONE_BAP_IND*/
   OsAppTask_event_100ms, /* CTA_APP_PHONE_FCT_PENDING*/
   OsAppTask_event_100ms, /* CTA_APP_PHONEBOOK_BAP_IND*/
   OsAppTask_event_100ms, /* CTA_APP_PHONEBOOK_FCT_PENDING*/
   OsAppTask_event_100ms, /* CTA_APP_MDI_BAP_IND*/
   OsAppTask_event_100ms, /* CTA_APP_MDI_FCT_PENDING*/
   OsAppTask_event_100ms, /* CTA_ERM_BT_VISIBILITY_TIMER*/
   OsSystemTask_event, /* CTA_SYSTEM*/
   OsHostTask_10ms, /* CTA_HOST_TASK_CYCLIC_CAN_TX_MSG*/
   OsAppTask_event_100ms, /* CTA_VCR_PENDING*/
   OsAppTask_event_100ms, /* CTA_ERM_PENDING*/
   OsAppTask_event_100ms, /* CTA_APP_PHONEBOOK_PB_INIT_PENDING*/
   OsDatabaseTask_event, /* CTA_WD*/
   OsAppTask_event_100ms, /* CTA_ASG_SV_TIMEOUT*/
   0, /* 0 for ALARMCALLBACK */
   OsAppTask_event_100ms, /* CTA_APP_SMS_FCT_PENDING*/
   OsAppTask_event_100ms, /* CTA_APP_PHONEBOOK_BAP_FCT_PENDING*/
   OsAppTask_event_100ms, /* CTA_APP_PHONE_BAP_FCT_PENDING*/
   OsMonitorTask_50ms, /* CTA_MONITOR_AUDIO*/
   OsAppTask_event_100ms, /* CTA_APP_SD_FCT_PENDING*/
   OsAppTask_event_100ms, /* CTA_KPB_FCT_PENDING*/
   OsAppTask_event_100ms, /* CTA_MFL_LONGPRESS_TIMER*/
   0, /* 0 for ALARMCALLBACK */
   OsAppTask_event_100ms, /* CTA_APP_DEVICE_FCT_PENDING*/
   OsAppTask_event_100ms, /* CTA_VCR_SUPERVISOR*/
   OsHostTask_10ms, /* CTA_HOST_TASK_CYCLIC_CAN_ASR_TX_MSG*/
   0, /* 0 for ALARMCALLBACK */
   OsHostTask_10ms, /* CTA_HOST_ASR_TRIGGER*/
   OsAppTask_event_100ms, /* CTA_APP_KPB_BAP_IND*/
   OsDriverTask_1ms, /* CTA_DRIVER_TIMER_10MS*/
   OsAppTask_event_100ms, /* CTA_CONTEXT_MAN_HANDLE_CALLS*/
   OsAppTask_event_100ms, /* CTA_APP_PHONEBOOK_BAP_ACT_PB_PEND*/
   0, /* 0 for ALARMCALLBACK */
   OsAppTask_event_100ms, /* CTA_APP_MDI_BAP_FCT_PENDING*/
   0, /* 0 for ALARMCALLBACK */
   0, /* 0 for ALARMCALLBACK */
   0, /* 0 for ALARMCALLBACK */
   0, /* 0 for ALARMCALLBACK */
   0, /* 0 for ALARMCALLBACK */
   OsAppTask_event_100ms, /* CTA_LOGI_BUT_MAN_ROLL_BUTTON*/
   0, /* 0 for ALARMCALLBACK */
   0, /* 0 for ALARMCALLBACK */
   0, /* 0 for ALARMCALLBACK */
   OsAppTask_event_100ms, /* CTA_APP_DIAG_RETRY_BUSY*/
   OsAppTask_event_100ms, /* CTA_APP_PHONE_BAP_REQUEST_PENDING*/
   OsHostTask_10ms, /* CTA_HOST_ONOFF_INFO_SLEEP_IND*/
   0, /* 0 for ALARMCALLBACK */
};
#else
 #if osdLib
 osqROM0 osqROM1 const osqROM2 TaskType osqROM3 oskAlarmTask[1]={0};
 #endif
#endif

#if osdNumberOfAlarmSetEvent > 0
osqROM0 osqROM1 const osqROM2 EventMaskType osqROM3 oskAlarmEvent[osdNumberOfAlarms]={
   evActivateHostTask_10ms, /* CTA_HOST*/
   evActivateMonitorTask_50ms, /* CTA_MONITOR*/
   evActivateDriverTask_1ms, /* CTA_DRIVER*/
   evDatabaseCyclicEepromWrite, /* CTA_DATABASE_EEPROM_WRITE*/
   evActivateAppTask_event_100ms, /* CTA_APP*/
   evAppTaskPhoneBapInd, /* CTA_APP_PHONE_BAP_IND*/
   evAppTaskPhoneFctPending, /* CTA_APP_PHONE_FCT_PENDING*/
   evAppTaskPhoneBookBapInd, /* CTA_APP_PHONEBOOK_BAP_IND*/
   evAppTaskPhoneBookFctPending, /* CTA_APP_PHONEBOOK_FCT_PENDING*/
   evAppTaskMdiBapInd, /* CTA_APP_MDI_BAP_IND*/
   evAppTaskMdiFctPending, /* CTA_APP_MDI_FCT_PENDING*/
   evAppTaskERMBTVisibleTimer, /* CTA_ERM_BT_VISIBILITY_TIMER*/
   evActivateSystemTask_event, /* CTA_SYSTEM*/
   evHostTaskCyclicTxMsg, /* CTA_HOST_TASK_CYCLIC_CAN_TX_MSG*/
   evAppTaskVCRPending, /* CTA_VCR_PENDING*/
   evAppTaskERMPending, /* CTA_ERM_PENDING*/
   evAppTaskPhoneBookBapFctPending, /* CTA_APP_PHONEBOOK_PB_INIT_PENDING*/
   evTriggerWD, /* CTA_WD*/
   evAppTaskKpbSupervision, /* CTA_ASG_SV_TIMEOUT*/
   0, /* 0 for ActivateTask or ALARMCALLBACK */
   evAppTaskSmsFctPending, /* CTA_APP_SMS_FCT_PENDING*/
   evAppTaskPhoneBookBapFctPending, /* CTA_APP_PHONEBOOK_BAP_FCT_PENDING*/
   evAppTaskPhoneBapFctPending, /* CTA_APP_PHONE_BAP_FCT_PENDING*/
   evMonitorTask_MonitorAudio_for_DTC, /* CTA_MONITOR_AUDIO*/
   evAppTaskSdFctPending, /* CTA_APP_SD_FCT_PENDING*/
   evAppTaskKpbPending, /* CTA_KPB_FCT_PENDING*/
   evAppTaskRollRadLongPressTimer, /* CTA_MFL_LONGPRESS_TIMER*/
   0, /* 0 for ActivateTask or ALARMCALLBACK */
   evAppTaskDeviceFctPending, /* CTA_APP_DEVICE_FCT_PENDING*/
   evAppTaskVCRSupervisor, /* CTA_VCR_SUPERVISOR*/
   evHostTaskASRCyclicTxMsg, /* CTA_HOST_TASK_CYCLIC_CAN_ASR_TX_MSG*/
   0, /* 0 for ActivateTask or ALARMCALLBACK */
   evHostTaskASRTrigger, /* CTA_HOST_ASR_TRIGGER*/
   evAppTaskKpbBapInd, /* CTA_APP_KPB_BAP_IND*/
   evDriverTask_TimerForButtonDetection_10ms, /* CTA_DRIVER_TIMER_10MS*/
   evAppTaskContaxtManHandleCalls, /* CTA_CONTEXT_MAN_HANDLE_CALLS*/
   evAppTaskPhoneBookBapFctPending, /* CTA_APP_PHONEBOOK_BAP_ACT_PB_PEND*/
   0, /* 0 for ActivateTask or ALARMCALLBACK */
   evAppTaskMdiBapFctPending, /* CTA_APP_MDI_BAP_FCT_PENDING*/
   0, /* 0 for ActivateTask or ALARMCALLBACK */
   0, /* 0 for ActivateTask or ALARMCALLBACK */
   0, /* 0 for ActivateTask or ALARMCALLBACK */
   0, /* 0 for ActivateTask or ALARMCALLBACK */
   0, /* 0 for ActivateTask or ALARMCALLBACK */
   evAppTaskMFLKeys, /* CTA_LOGI_BUT_MAN_ROLL_BUTTON*/
   0, /* 0 for ActivateTask or ALARMCALLBACK */
   0, /* 0 for ActivateTask or ALARMCALLBACK */
   0, /* 0 for ActivateTask or ALARMCALLBACK */
   evAppTaskDiagnoseRequest, /* CTA_APP_DIAG_RETRY_BUSY*/
   evAppTaskPhoneBapRequestPending, /* CTA_APP_PHONE_BAP_REQUEST_PENDING*/
   evHostTaskOnOffInfoSleepInd, /* CTA_HOST_ONOFF_INFO_SLEEP_IND*/
   0, /* 0 for ActivateTask or ALARMCALLBACK */
};
#else
 #if osdLib
 osqROM0 osqROM1 const osqROM2 EventMaskType osqROM3 oskAlarmEvent[1]={0};
 #endif
#endif

#if osdNumberOfAlarmCallback > 0
/* alarm callback function */
osqROM0 osAlarmCallbackType osqROM1 const osqROM2 osqROM3 oskAlarmCallback[osdNumberOfAlarms]={
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   KPB_cbFrameDataAckTimeout, /* CTA_FRAME_DATA_ACK_TIMEOUT*/
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   APP_SD_cbFrameTimeout, /* CTA_APP_SD_FRAME_TIMEOUT*/
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   ERM_UartSupervision, /* CTA_UART_SUPERVISION*/
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   APP_DIAG_vHandlePendingResponseFromApplication, /* CTA_APP_DIAG_WAIT_FOR_APP_CB*/
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   KPB_cbDisplayStatusOff, /* CTA_KPB_DISPLAY_STATUS_OFF*/
   ctaERMStopJingle_cb, /* CTA_ERM_STOP_JINGLE*/
   APP_PHONE_cbOutgoingCallIndicationTimeout, /* CTA_APP_PHONE_OUTGOING_CALL_INDICATION_TIMER*/
   ctaBtTimeout_cb, /* CTA_BTMOD_TIMEOUT*/
   APP_PHONE_cbOnPatrTimeout, /* CTA_APP_PHONE_PATR_WORKAROUND_TIMER*/
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   APP_PHONEBOOK_cbPbSortingTimeout, /* CTA_APP_PHONEBOOK_SORTING_TIMEOUT*/
   APP_CAN_cbNachlaufzeitTimeout, /* CTA_APP_CAN_TO_NACHLAUFZEIT*/
   SDS_UDS_RetryMechanismR2FS, /* CTA_HOST_R2FS_DIAG_RETRY*/
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   (osAlarmCallbackType) osdNULL, /* 0 for ActivateTask or SetEvent */
   SDS_UDS_Wait_DEH_Write_Finish, /* CTA_DEH_EE_WRITE_TIME*/
};
#else
 #if osdLib
 osqROM0 osAlarmCallbackType osqROM1 const osqROM2 osqROM3 oskAlarmCallback[1]={(osAlarmCallbackType)0};
 #endif
#endif

#if (osdNumberOfAlarmCallback > 0) || (osdNumberOfAlarmSetEvent > 0)
osqROM0 osqROM1 const osqROM2 uint8 osqROM3 oskAlarmAction[osdNumberOfAlarms]={
   osdAlarmActionSetEvent, /* CTA_HOST*/
   osdAlarmActionSetEvent, /* CTA_MONITOR*/
   osdAlarmActionSetEvent, /* CTA_DRIVER*/
   osdAlarmActionSetEvent, /* CTA_DATABASE_EEPROM_WRITE*/
   osdAlarmActionSetEvent, /* CTA_APP*/
   osdAlarmActionSetEvent, /* CTA_APP_PHONE_BAP_IND*/
   osdAlarmActionSetEvent, /* CTA_APP_PHONE_FCT_PENDING*/
   osdAlarmActionSetEvent, /* CTA_APP_PHONEBOOK_BAP_IND*/
   osdAlarmActionSetEvent, /* CTA_APP_PHONEBOOK_FCT_PENDING*/
   osdAlarmActionSetEvent, /* CTA_APP_MDI_BAP_IND*/
   osdAlarmActionSetEvent, /* CTA_APP_MDI_FCT_PENDING*/
   osdAlarmActionSetEvent, /* CTA_ERM_BT_VISIBILITY_TIMER*/
   osdAlarmActionSetEvent, /* CTA_SYSTEM*/
   osdAlarmActionSetEvent, /* CTA_HOST_TASK_CYCLIC_CAN_TX_MSG*/
   osdAlarmActionSetEvent, /* CTA_VCR_PENDING*/
   osdAlarmActionSetEvent, /* CTA_ERM_PENDING*/
   osdAlarmActionSetEvent, /* CTA_APP_PHONEBOOK_PB_INIT_PENDING*/
   osdAlarmActionSetEvent, /* CTA_WD*/
   osdAlarmActionSetEvent, /* CTA_ASG_SV_TIMEOUT*/
   osdAlarmActionCallback, /* CTA_FRAME_DATA_ACK_TIMEOUT*/
   osdAlarmActionSetEvent, /* CTA_APP_SMS_FCT_PENDING*/
   osdAlarmActionSetEvent, /* CTA_APP_PHONEBOOK_BAP_FCT_PENDING*/
   osdAlarmActionSetEvent, /* CTA_APP_PHONE_BAP_FCT_PENDING*/
   osdAlarmActionSetEvent, /* CTA_MONITOR_AUDIO*/
   osdAlarmActionSetEvent, /* CTA_APP_SD_FCT_PENDING*/
   osdAlarmActionSetEvent, /* CTA_KPB_FCT_PENDING*/
   osdAlarmActionSetEvent, /* CTA_MFL_LONGPRESS_TIMER*/
   osdAlarmActionCallback, /* CTA_APP_SD_FRAME_TIMEOUT*/
   osdAlarmActionSetEvent, /* CTA_APP_DEVICE_FCT_PENDING*/
   osdAlarmActionSetEvent, /* CTA_VCR_SUPERVISOR*/
   osdAlarmActionSetEvent, /* CTA_HOST_TASK_CYCLIC_CAN_ASR_TX_MSG*/
   osdAlarmActionCallback, /* CTA_UART_SUPERVISION*/
   osdAlarmActionSetEvent, /* CTA_HOST_ASR_TRIGGER*/
   osdAlarmActionSetEvent, /* CTA_APP_KPB_BAP_IND*/
   osdAlarmActionSetEvent, /* CTA_DRIVER_TIMER_10MS*/
   osdAlarmActionSetEvent, /* CTA_CONTEXT_MAN_HANDLE_CALLS*/
   osdAlarmActionSetEvent, /* CTA_APP_PHONEBOOK_BAP_ACT_PB_PEND*/
   osdAlarmActionCallback, /* CTA_APP_DIAG_WAIT_FOR_APP_CB*/
   osdAlarmActionSetEvent, /* CTA_APP_MDI_BAP_FCT_PENDING*/
   osdAlarmActionCallback, /* CTA_KPB_DISPLAY_STATUS_OFF*/
   osdAlarmActionCallback, /* CTA_ERM_STOP_JINGLE*/
   osdAlarmActionCallback, /* CTA_APP_PHONE_OUTGOING_CALL_INDICATION_TIMER*/
   osdAlarmActionCallback, /* CTA_BTMOD_TIMEOUT*/
   osdAlarmActionCallback, /* CTA_APP_PHONE_PATR_WORKAROUND_TIMER*/
   osdAlarmActionSetEvent, /* CTA_LOGI_BUT_MAN_ROLL_BUTTON*/
   osdAlarmActionCallback, /* CTA_APP_PHONEBOOK_SORTING_TIMEOUT*/
   osdAlarmActionCallback, /* CTA_APP_CAN_TO_NACHLAUFZEIT*/
   osdAlarmActionCallback, /* CTA_HOST_R2FS_DIAG_RETRY*/
   osdAlarmActionSetEvent, /* CTA_APP_DIAG_RETRY_BUSY*/
   osdAlarmActionSetEvent, /* CTA_APP_PHONE_BAP_REQUEST_PENDING*/
   osdAlarmActionSetEvent, /* CTA_HOST_ONOFF_INFO_SLEEP_IND*/
   osdAlarmActionCallback, /* CTA_DEH_EE_WRITE_TIME*/
};
#else
 #if (osdNumberOfAlarms == 0) || osdLib
  osqROM0 osqROM1 const osqROM2 uint8 osqROM3 oskAlarmAction[1]={0};
 #endif
#endif

/* static alarm time */
osqROM0 osqROM1 const osqROM2 TickType osqROM3 oskStaticAlarmTime[osdNumberOfAlarms]={
   0, /* no static alarm: CTA_HOST*/
   0, /* no static alarm: CTA_MONITOR*/
   0, /* no static alarm: CTA_DRIVER*/
   0, /* no static alarm: CTA_DATABASE_EEPROM_WRITE*/
   0, /* no static alarm: CTA_APP*/
   0, /* no static alarm: CTA_APP_PHONE_BAP_IND*/
   0, /* no static alarm: CTA_APP_PHONE_FCT_PENDING*/
   0, /* no static alarm: CTA_APP_PHONEBOOK_BAP_IND*/
   0, /* no static alarm: CTA_APP_PHONEBOOK_FCT_PENDING*/
   0, /* no static alarm: CTA_APP_MDI_BAP_IND*/
   0, /* no static alarm: CTA_APP_MDI_FCT_PENDING*/
   0, /* no static alarm: CTA_ERM_BT_VISIBILITY_TIMER*/
   0, /* no static alarm: CTA_SYSTEM*/
   0, /* no static alarm: CTA_HOST_TASK_CYCLIC_CAN_TX_MSG*/
   0, /* no static alarm: CTA_VCR_PENDING*/
   0, /* no static alarm: CTA_ERM_PENDING*/
   0, /* no static alarm: CTA_APP_PHONEBOOK_PB_INIT_PENDING*/
   0, /* no static alarm: CTA_WD*/
   0, /* no static alarm: CTA_ASG_SV_TIMEOUT*/
   0, /* no static alarm: CTA_FRAME_DATA_ACK_TIMEOUT*/
   0, /* no static alarm: CTA_APP_SMS_FCT_PENDING*/
   0, /* no static alarm: CTA_APP_PHONEBOOK_BAP_FCT_PENDING*/
   0, /* no static alarm: CTA_APP_PHONE_BAP_FCT_PENDING*/
   0, /* no static alarm: CTA_MONITOR_AUDIO*/
   0, /* no static alarm: CTA_APP_SD_FCT_PENDING*/
   0, /* no static alarm: CTA_KPB_FCT_PENDING*/
   0, /* no static alarm: CTA_MFL_LONGPRESS_TIMER*/
   0, /* no static alarm: CTA_APP_SD_FRAME_TIMEOUT*/
   0, /* no static alarm: CTA_APP_DEVICE_FCT_PENDING*/
   0, /* no static alarm: CTA_VCR_SUPERVISOR*/
   0, /* no static alarm: CTA_HOST_TASK_CYCLIC_CAN_ASR_TX_MSG*/
   0, /* no static alarm: CTA_UART_SUPERVISION*/
   0, /* no static alarm: CTA_HOST_ASR_TRIGGER*/
   0, /* no static alarm: CTA_APP_KPB_BAP_IND*/
   0, /* no static alarm: CTA_DRIVER_TIMER_10MS*/
   0, /* no static alarm: CTA_CONTEXT_MAN_HANDLE_CALLS*/
   0, /* no static alarm: CTA_APP_PHONEBOOK_BAP_ACT_PB_PEND*/
   0, /* no static alarm: CTA_APP_DIAG_WAIT_FOR_APP_CB*/
   0, /* no static alarm: CTA_APP_MDI_BAP_FCT_PENDING*/
   0, /* no static alarm: CTA_KPB_DISPLAY_STATUS_OFF*/
   0, /* no static alarm: CTA_ERM_STOP_JINGLE*/
   0, /* no static alarm: CTA_APP_PHONE_OUTGOING_CALL_INDICATION_TIMER*/
   0, /* no static alarm: CTA_BTMOD_TIMEOUT*/
   0, /* no static alarm: CTA_APP_PHONE_PATR_WORKAROUND_TIMER*/
   0, /* no static alarm: CTA_LOGI_BUT_MAN_ROLL_BUTTON*/
   0, /* no static alarm: CTA_APP_PHONEBOOK_SORTING_TIMEOUT*/
   0, /* no static alarm: CTA_APP_CAN_TO_NACHLAUFZEIT*/
   0, /* no static alarm: CTA_HOST_R2FS_DIAG_RETRY*/
   0, /* no static alarm: CTA_APP_DIAG_RETRY_BUSY*/
   0, /* no static alarm: CTA_APP_PHONE_BAP_REQUEST_PENDING*/
   0, /* no static alarm: CTA_HOST_ONOFF_INFO_SLEEP_IND*/
   0, /* no static alarm: CTA_DEH_EE_WRITE_TIME*/
};

/* static cycle time */
osqROM0 osqROM1 const osqROM2 TickType osqROM3 oskStaticAlarmCycleTime[osdNumberOfAlarms]={
   0, /* no static alarm: CTA_HOST */
   0, /* no static alarm: CTA_MONITOR */
   0, /* no static alarm: CTA_DRIVER */
   0, /* no static alarm: CTA_DATABASE_EEPROM_WRITE */
   0, /* no static alarm: CTA_APP */
   0, /* no static alarm: CTA_APP_PHONE_BAP_IND */
   0, /* no static alarm: CTA_APP_PHONE_FCT_PENDING */
   0, /* no static alarm: CTA_APP_PHONEBOOK_BAP_IND */
   0, /* no static alarm: CTA_APP_PHONEBOOK_FCT_PENDING */
   0, /* no static alarm: CTA_APP_MDI_BAP_IND */
   0, /* no static alarm: CTA_APP_MDI_FCT_PENDING */
   0, /* no static alarm: CTA_ERM_BT_VISIBILITY_TIMER */
   0, /* no static alarm: CTA_SYSTEM */
   0, /* no static alarm: CTA_HOST_TASK_CYCLIC_CAN_TX_MSG */
   0, /* no static alarm: CTA_VCR_PENDING */
   0, /* no static alarm: CTA_ERM_PENDING */
   0, /* no static alarm: CTA_APP_PHONEBOOK_PB_INIT_PENDING */
   0, /* no static alarm: CTA_WD */
   0, /* no static alarm: CTA_ASG_SV_TIMEOUT */
   0, /* no static alarm: CTA_FRAME_DATA_ACK_TIMEOUT */
   0, /* no static alarm: CTA_APP_SMS_FCT_PENDING */
   0, /* no static alarm: CTA_APP_PHONEBOOK_BAP_FCT_PENDING */
   0, /* no static alarm: CTA_APP_PHONE_BAP_FCT_PENDING */
   0, /* no static alarm: CTA_MONITOR_AUDIO */
   0, /* no static alarm: CTA_APP_SD_FCT_PENDING */
   0, /* no static alarm: CTA_KPB_FCT_PENDING */
   0, /* no static alarm: CTA_MFL_LONGPRESS_TIMER */
   0, /* no static alarm: CTA_APP_SD_FRAME_TIMEOUT */
   0, /* no static alarm: CTA_APP_DEVICE_FCT_PENDING */
   0, /* no static alarm: CTA_VCR_SUPERVISOR */
   0, /* no static alarm: CTA_HOST_TASK_CYCLIC_CAN_ASR_TX_MSG */
   0, /* no static alarm: CTA_UART_SUPERVISION */
   0, /* no static alarm: CTA_HOST_ASR_TRIGGER */
   0, /* no static alarm: CTA_APP_KPB_BAP_IND */
   0, /* no static alarm: CTA_DRIVER_TIMER_10MS */
   0, /* no static alarm: CTA_CONTEXT_MAN_HANDLE_CALLS */
   0, /* no static alarm: CTA_APP_PHONEBOOK_BAP_ACT_PB_PEND */
   0, /* no static alarm: CTA_APP_DIAG_WAIT_FOR_APP_CB */
   0, /* no static alarm: CTA_APP_MDI_BAP_FCT_PENDING */
   0, /* no static alarm: CTA_KPB_DISPLAY_STATUS_OFF */
   0, /* no static alarm: CTA_ERM_STOP_JINGLE */
   0, /* no static alarm: CTA_APP_PHONE_OUTGOING_CALL_INDICATION_TIMER */
   0, /* no static alarm: CTA_BTMOD_TIMEOUT */
   0, /* no static alarm: CTA_APP_PHONE_PATR_WORKAROUND_TIMER */
   0, /* no static alarm: CTA_LOGI_BUT_MAN_ROLL_BUTTON */
   0, /* no static alarm: CTA_APP_PHONEBOOK_SORTING_TIMEOUT */
   0, /* no static alarm: CTA_APP_CAN_TO_NACHLAUFZEIT */
   0, /* no static alarm: CTA_HOST_R2FS_DIAG_RETRY */
   0, /* no static alarm: CTA_APP_DIAG_RETRY_BUSY */
   0, /* no static alarm: CTA_APP_PHONE_BAP_REQUEST_PENDING */
   0, /* no static alarm: CTA_HOST_ONOFF_INFO_SLEEP_IND */
   0, /* no static alarm: CTA_DEH_EE_WRITE_TIME */
};

/* Autostart */
osqROM0 osqROM1 const osqROM2 uint8 osqROM3 oskAlarmAutoStart[osdNumberOfAlarms]={
   0x00, /* CTA_HOST */
   0x00, /* CTA_MONITOR */
   0x00, /* CTA_DRIVER */
   0x00, /* CTA_DATABASE_EEPROM_WRITE */
   0x00, /* CTA_APP */
   0x00, /* CTA_APP_PHONE_BAP_IND */
   0x00, /* CTA_APP_PHONE_FCT_PENDING */
   0x00, /* CTA_APP_PHONEBOOK_BAP_IND */
   0x00, /* CTA_APP_PHONEBOOK_FCT_PENDING */
   0x00, /* CTA_APP_MDI_BAP_IND */
   0x00, /* CTA_APP_MDI_FCT_PENDING */
   0x00, /* CTA_ERM_BT_VISIBILITY_TIMER */
   0x00, /* CTA_SYSTEM */
   0x00, /* CTA_HOST_TASK_CYCLIC_CAN_TX_MSG */
   0x00, /* CTA_VCR_PENDING */
   0x00, /* CTA_ERM_PENDING */
   0x00, /* CTA_APP_PHONEBOOK_PB_INIT_PENDING */
   0x00, /* CTA_WD */
   0x00, /* CTA_ASG_SV_TIMEOUT */
   0x00, /* CTA_FRAME_DATA_ACK_TIMEOUT */
   0x00, /* CTA_APP_SMS_FCT_PENDING */
   0x00, /* CTA_APP_PHONEBOOK_BAP_FCT_PENDING */
   0x00, /* CTA_APP_PHONE_BAP_FCT_PENDING */
   0x00, /* CTA_MONITOR_AUDIO */
   0x00, /* CTA_APP_SD_FCT_PENDING */
   0x00, /* CTA_KPB_FCT_PENDING */
   0x00, /* CTA_MFL_LONGPRESS_TIMER */
   0x00, /* CTA_APP_SD_FRAME_TIMEOUT */
   0x00, /* CTA_APP_DEVICE_FCT_PENDING */
   0x00, /* CTA_VCR_SUPERVISOR */
   0x00, /* CTA_HOST_TASK_CYCLIC_CAN_ASR_TX_MSG */
   0x00, /* CTA_UART_SUPERVISION */
   0x00, /* CTA_HOST_ASR_TRIGGER */
   0x00, /* CTA_APP_KPB_BAP_IND */
   0x00, /* CTA_DRIVER_TIMER_10MS */
   0x00, /* CTA_CONTEXT_MAN_HANDLE_CALLS */
   0x00, /* CTA_APP_PHONEBOOK_BAP_ACT_PB_PEND */
   0x00, /* CTA_APP_DIAG_WAIT_FOR_APP_CB */
   0x00, /* CTA_APP_MDI_BAP_FCT_PENDING */
   0x00, /* CTA_KPB_DISPLAY_STATUS_OFF */
   0x00, /* CTA_ERM_STOP_JINGLE */
   0x00, /* CTA_APP_PHONE_OUTGOING_CALL_INDICATION_TIMER */
   0x00, /* CTA_BTMOD_TIMEOUT */
   0x00, /* CTA_APP_PHONE_PATR_WORKAROUND_TIMER */
   0x00, /* CTA_LOGI_BUT_MAN_ROLL_BUTTON */
   0x00, /* CTA_APP_PHONEBOOK_SORTING_TIMEOUT */
   0x00, /* CTA_APP_CAN_TO_NACHLAUFZEIT */
   0x00, /* CTA_HOST_R2FS_DIAG_RETRY */
   0x00, /* CTA_APP_DIAG_RETRY_BUSY */
   0x00, /* CTA_APP_PHONE_BAP_REQUEST_PENDING */
   0x00, /* CTA_HOST_ONOFF_INFO_SLEEP_IND */
   0x00, /* CTA_DEH_EE_WRITE_TIME */
};


#if (osdGHSDebugSupport==1)
osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 * osqROM1 const osqROM2 osqROM3 oskAlarmName[osdNumberOfAlarms]=
{
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_HOST",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_MONITOR",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_DRIVER",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_DATABASE_EEPROM_WRITE",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_APP",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_APP_PHONE_BAP_IND",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_APP_PHONE_FCT_PENDING",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_APP_PHONEBOOK_BAP_IND",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_APP_PHONEBOOK_FCT_PENDING",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_APP_MDI_BAP_IND",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_APP_MDI_FCT_PENDING",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_ERM_BT_VISIBILITY_TIMER",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_SYSTEM",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_HOST_TASK_CYCLIC_CAN_TX_MSG",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_VCR_PENDING",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_ERM_PENDING",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_APP_PHONEBOOK_PB_INIT_PENDING",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_WD",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_ASG_SV_TIMEOUT",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_FRAME_DATA_ACK_TIMEOUT",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_APP_SMS_FCT_PENDING",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_APP_PHONEBOOK_BAP_FCT_PENDING",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_APP_PHONE_BAP_FCT_PENDING",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_MONITOR_AUDIO",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_APP_SD_FCT_PENDING",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_KPB_FCT_PENDING",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_MFL_LONGPRESS_TIMER",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_APP_SD_FRAME_TIMEOUT",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_APP_DEVICE_FCT_PENDING",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_VCR_SUPERVISOR",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_HOST_TASK_CYCLIC_CAN_ASR_TX_MSG",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_UART_SUPERVISION",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_HOST_ASR_TRIGGER",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_APP_KPB_BAP_IND",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_DRIVER_TIMER_10MS",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_CONTEXT_MAN_HANDLE_CALLS",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_APP_PHONEBOOK_BAP_ACT_PB_PEND",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_APP_DIAG_WAIT_FOR_APP_CB",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_APP_MDI_BAP_FCT_PENDING",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_KPB_DISPLAY_STATUS_OFF",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_ERM_STOP_JINGLE",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_APP_PHONE_OUTGOING_CALL_INDICATION_TIMER",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_BTMOD_TIMEOUT",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_APP_PHONE_PATR_WORKAROUND_TIMER",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_LOGI_BUT_MAN_ROLL_BUTTON",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_APP_PHONEBOOK_SORTING_TIMEOUT",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_APP_CAN_TO_NACHLAUFZEIT",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_HOST_R2FS_DIAG_RETRY",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_APP_DIAG_RETRY_BUSY",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_APP_PHONE_BAP_REQUEST_PENDING",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_HOST_ONOFF_INFO_SLEEP_IND",
   (osqROM0 osqPROM1 const osqPROM2 uint8 osqPROM3 *)"CTA_DEH_EE_WRITE_TIME",
};

#endif

osqFunc1 void osqFunc2 osInitTimer(void)
{

   *((volatile uint32*)osdRTICINT) &=~osdRTICmpENA;				/* disable compare interrupt */
   *((volatile uint32*)osdREQMASK) &=~osdRTIIntFlag;   /* disable interrupt */
   *((volatile uint32*)osdFIRQPR)  &=~osdRTIIntFlag;   			/* interrupt is IRQ */
   *((volatile uint32*)osdRTIPCTL)  = (*((volatile uint32*)osdRTIPCTL) & 0xfffff800) | osdClockDividerReg;   /* set prescaler */
   *((volatile uint32*)osdRTICMP)   = (*((volatile uint32*)osdRTICNTR) >> 11) + osdClockReloadReg;   /* RTICMPx */
   *((volatile uint32*)osdRTICINT) &=~osdRTICmpFlag;   			/* clear compare flag */
   *((volatile uint32*)osdINTREQ)  &=~osdRTIIntFlag;   			/* clear pending flag */
   *((volatile uint32*)osdREQMASK) |= osdRTIIntFlag;   /* enable interrupt  */
   *((volatile uint32*)osdRTICINT) |= osdRTICmpENA;   			/* enable compare interrupt */
   *((volatile uint32*)osdRTICNTEN) = 0;						/* count enable */
}/*ENDOF osInitTimer*/



ISR(osTimerInt) /* PRQA S 1503 */  /* called from assembler code */
{

   OS_TI_ENTRY();

   *((volatile uint32*)osdREQMASK) &=~osdRTIIntFlag;   /* disable interrupt */
   *((volatile uint32*)osdRTICMP) = (*((volatile uint32*)osdRTICMP) & 0x1fffff) + osdClockReloadReg;   /* RTICMPx */
   *((volatile uint32*)osdRTICINT) &= ~osdRTICmpFlag;   		/* clear compare flag */
#if osdUseCounterAPI
   osCounter[SystemTimer]++;
#else
   osSystemCounter++;
#endif
#if (osdNumberOfAlarms > 0)
#ifndef osdUseGeneratedFastAlarm
 #if (osdEnableIntNesting==0)
   osEnableLevel();
 #endif
   osWorkAlarms();
 #if (osdEnableIntNesting==0)
   osDisableLevel();
 #endif
#else
 #if (osdEnableIntNesting==1)
   osDisableLevel();
 #endif
   osCheckAlarms();
 #if (osdEnableIntNesting==1)
   osSetAlarmLevel();
 #endif
#endif
#endif
   *((volatile uint32*)osdREQMASK) |= osdRTIIntFlag;   /* enable interrupt  */
   OS_TI_EXIT();
}/*ENDOF osTimerInt*/


osqFunc1 void osqFunc2 osInitISRprios(void)
{
}

/* END OF C:\PROGRAMME\ECLIPSE-CPP\ECLIPSE\WORKSPACE\UHV-NAR\MOD\MOD_OSEK_DYN\CFG\tcb\tcb.c */

