/****************************************************************************/
/* @Controller    Infineon TC1766 */
/* */
/* @Compiler      Tasking */
/* */
/* @Codegenerator 2.0.2 */
/* */
/* @Description   This file contains CAS data types definition. */
/* */
/*--------------------------------------------------------------------------*/
/* @Date          02.12.2004 13:45:40 */
/* */
/****************************************************************************/
/*
|
| Subversion Info:
| $Id: DTYP.H 4396 2008-11-04 09:26:32Z maennel $
| $HeadURL: http://smartsvn/svn/adlatusrepository/auslieferungen/S1NN/086350-S1NN-ADLATUS-TMS470R-MucSuc/20081201_S1NN_TMS470R_BlfIso-Source_V1.00/01_SW_Projekt/05_header/ext/DTYP.H $
|
*/ 

#ifndef CAS_DTYP_H_
#define CAS_DTYP_H_

/****************************************************************************/
/* @Project Includes */
/****************************************************************************/


/****************************************************************************/
/* @Defines */
/****************************************************************************/

typedef void T_V ;
typedef signed char T_S8 ;
typedef unsigned char T_U8 ;
typedef signed short T_S16 ;
typedef unsigned short  T_U16 ;
typedef signed long T_S32 ;
typedef unsigned long T_U32 ;
/*typedef  T_S64 ;*/
typedef float T_F32 ;
typedef double T_F64 ;




#endif  
